import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core'

export const events = sqliteTable('events', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  start: integer('start', { mode: 'timestamp' }).notNull(),
  end: integer('end', { mode: 'timestamp' }),
  org: text('org').notNull().default(''),
  orgUrl: text('org_url').notNull().default(''),
  type: text('type').notNull().default(''),
  club: text('club').notNull().default(''),
  location: text('location').notNull().default(''),
  url: text('url').notNull().default(''),
  description: text('description').notNull().default(''),
})

export type EventRow = typeof events.$inferSelect

/** A saved conversation. Titles are generated by an AIR model from the opening prompt. */
export const conversations = sqliteTable('conversations', {
  id: text('id').primaryKey(),
  /** Owning ASURITE. Conversations are per-account, never shared. */
  asurite: text('asurite').notNull().default(''),
  title: text('title').notNull().default('New chat'),
  pinned: integer('pinned', { mode: 'boolean' }).notNull().default(false),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
})

export const messages = sqliteTable('messages', {
  id: text('id').primaryKey(),
  conversationId: text('conversation_id')
    .notNull()
    .references(() => conversations.id, { onDelete: 'cascade' }),
  role: text('role', { enum: ['user', 'assistant'] }).notNull(),
  content: text('content').notNull().default(''),
  /** 'events' when the scripted shortlist was shown, 'vision' for an image reply. */
  kind: text('kind').notNull().default('text'),
  imageName: text('image_name'),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
})

export type ConversationRow = typeof conversations.$inferSelect
export type MessageRow = typeof messages.$inferSelect

/**
 * Remembers models the gateway has refused outright (unknown model, modality
 * not supported) so we stop paying the round trip. Slowness and cold starts are
 * deliberately NOT recorded here — a slow model is still a working model.
 */
export const modelHealth = sqliteTable('model_health', {
  model: text('model').primaryKey(),
  service: text('service').notNull(),
  reason: text('reason').notNull().default(''),
  status: integer('status'),
  disabledUntil: integer('disabled_until', { mode: 'timestamp' }).notNull(),
  checkedAt: integer('checked_at', { mode: 'timestamp' }).notNull(),
})

export type ModelHealthRow = typeof modelHealth.$inferSelect

/**
 * Admin overrides for which AIR model serves each capability.
 *
 * A row here is a *preference*, not a lock: the runner still falls back through
 * the compiled-in list in lib/air/models.ts when the chosen model is refused by
 * the gateway. An admin picking badly slows a request down; it cannot take the
 * app offline.
 */
export const modelSettings = sqliteTable('model_settings', {
  /** An AirService name — 'chat', 'vision', 'asr', … */
  service: text('service').primaryKey(),
  model: text('model').notNull(),
  /** ASURITE of the admin who set it, for the audit line in the UI. */
  updatedBy: text('updated_by').notNull().default(''),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
})

export type ModelSettingRow = typeof modelSettings.$inferSelect

/**
 * Which registry tools this app exposes to the model.
 *
 * Absence means enabled: a tool newly registered in asu-tools-api is available
 * without anyone visiting the dashboard, and only an explicit "off" is stored.
 * The registry stays the source of truth for what *exists*; this decides what
 * Sol is allowed to reach for.
 */
export const toolSettings = sqliteTable('tool_settings', {
  name: text('name').primaryKey(),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
  updatedBy: text('updated_by').notNull().default(''),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
})

export type ToolSettingRow = typeof toolSettings.$inferSelect
